# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

stages:
- stage: Main
  displayName: "The main and only job"
  pool:
    vmImage: ununtu-latest
  jobs:
  - job:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '5.0.x'

      
